id: IF52BBF22
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:27:38+00:00'
last_modified: '2022-06-08T13:18:15.412801+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4996
  title: སྤྱོད་འཇུག་ཤེས་རབ་ལེའུའི་ཚིག་དོན་གོ་སླར་བཤད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8168':
      image_group_id: I1KG10345
      title: ''
      total_pages: 597
      order: 1
      base_file: 8168.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
