id: P010398
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:47:43.672928
source_metadata:
  id: bdr:W4996
  title: སྤྱོད་འཇུག་ཤེས་རབ་ལེའུའི་ཚིག་དོན་གོ་སླར་བཤད་པ།
  author: ''
  volumes:
    e3e7d5276f1a4adcac42a105bc8877e1:
      image_group_id: I1KG10345
      title: ''
      volume_number: 1
      total_pages: 597
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
