id: P010398
initial_creation_type: ocr
source_metadata:
  id: bdr:W4996
  title: སྤྱོད་འཇུག་ཤེས་རབ་ལེའུའི་ཚིག་དོན་གོ་སླར་བཤད་པ།
  author: ''
  volumes:
    e3e7d5276f1a4adcac42a105bc8877e1:
      image_group_id: I1KG10345
      title: ''
      volume_number: 1
      total_pages: 597
      base_file: v001.txt
